# Generated by Django 4.1.1 on 2022-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='As a new user, kindly update your profile to reflect your bio.', max_length=300),
        ),
    ]
